/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import com.sun.glass.events.KeyEvent;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import static productos.OpcionesAl.cn;
import static productos.OpcionesAl.ps;
import usuarios.*;
import ventas.CajaAd;

/**
 *
 * @author Rojeru San CL
 */


public class ListaTipo extends javax.swing.JInternalFrame {

    static int opcion =0;
    
    public ListaTipo() {
        initComponents();
        this.setLocation(700,55);
        if(opcion==0){
            this.setTitle("NUEVO TIPO");
            this.setSize(this.getWidth()-80, this.getHeight());
            borrar.setVisible(false);
           
        }
        else {
            this.setTitle("ACTUALIZAR / ELIMINAR TIPO "+ productos.Productos.tipoAl1.getSelectedItem());
            mas.setIcon(new ImageIcon(getClass().getResource("/imagenes/Productos/actualizar1.png")));
             mas.setRolloverIcon(new ImageIcon(getClass().getResource("/imagenes/Productos/actualizar2.png")));
        }
             
    }
    
    
    
    void registrar(){
         if(nuevo_tipo.getText().equals(""))
                    JOptionPane.showMessageDialog(this, "Campo no puede estar vacio", "Almacen", 0,
                    new ImageIcon(getClass().getResource("/imagenes/usuarios/info.png")));
         else if(existe_nuevo(nuevo_tipo.getText()))
              JOptionPane.showMessageDialog(this, "El tipo ya existe intente de nuevo", "Error", 0,
                            new ImageIcon(getClass().getResource("/imagenes/usuarios/seguro.png")));
         else
         try{
          Statement st = cn.createStatement();
          String sql="";
          
          
          if(opcion==0) sql="INSERT INTO tipo_producto(tipo) VALUES ('"+nuevo_tipo.getText()+"')";
          else{ sql="UPDATE tipo_producto SET tipo= '"+nuevo_tipo.getText()+"' where tipo='"+productos.Productos.tipoAl1.getSelectedItem().toString()+"'";
                productos.Productos.tipoAl1.removeItemAt(productos.Productos.tipoAl1.getSelectedIndex());}
         // System.out.println(productos.Productos.tipoAl1.getSelectedItem().toString());
          PreparedStatement ps = cn.prepareStatement(sql);
           
           ps.executeUpdate();
          
          productos.Productos.tipoAl1.addItem(nuevo_tipo.getText());
           productos.Productos.tipoAl1.setSelectedIndex( productos.Productos.tipoAl1.getItemCount()-1);
           
           
         
           this.dispose();
           
          }catch(Exception e){
          System.out.print(""+e);
          }
    }
     boolean existe_nuevo(String nuevo){
          try {
            String sql = "SELECT tipo FROM tipo_producto WHERE tipo = '" + nuevo + "'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            if (rs.next()) {
              return true;  
            }
          }catch(Exception e){}
         
         
         return false;
     }
    
  void eliminar(String tipo){
      
            if (JOptionPane.showConfirmDialog(this, "Esta a punto de eliminar el tipo: "+tipo+".\n¿Desea continuar?", "Eliminar", JOptionPane.YES_NO_OPTION, 0,
                    new ImageIcon(getClass().getResource("/imagenes/usuarios/seguro.png"))) == JOptionPane.YES_OPTION) {
                try{
                    String sql="DELETE FROM tipo_producto WHERE tipo = '"+tipo+"'";
          
                    PreparedStatement ps = cn.prepareStatement(sql);           
                    ps.executeUpdate(); 
                    productos.Productos.tipoAl1.removeItemAt(productos.Productos.tipoAl1.getSelectedIndex());
                    productos.Productos.tipoAl1.setSelectedIndex(0);     
         
                    this.dispose();
                
                    
                    JOptionPane.showMessageDialog(this, "Tipo eliminado.", "Eliminar", 0,
                            new ImageIcon(getClass().getResource("/imagenes/Productos/borrado.png")));
                     }catch(Exception e){System.out.println(""+e);}
                  }
       
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mas = new javax.swing.JButton();
        nuevo_tipo = new app.bolivia.swing.JCTextField();
        nombreL = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("NUEVO TIPO");
        setName("d"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        mas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos/mas1.png"))); // NOI18N
        mas.setBorder(null);
        mas.setBorderPainted(false);
        mas.setContentAreaFilled(false);
        mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos/mas2.png"))); // NOI18N
        mas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        nuevo_tipo.setBackground(new java.awt.Color(34, 102, 145));
        nuevo_tipo.setBorder(null);
        nuevo_tipo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo_tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nuevo_tipo.setOpaque(false);
        nuevo_tipo.setPhColor(new java.awt.Color(255, 255, 255));
        nuevo_tipo.setPlaceholder("TIPO");
        nuevo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_tipoActionPerformed(evt);
            }
        });
        nuevo_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuevo_tipoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nuevo_tipoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nuevo_tipoKeyTyped(evt);
            }
        });

        nombreL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos/nombreL.png"))); // NOI18N

        borrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos/borrar1.png"))); // NOI18N
        borrar.setBorder(null);
        borrar.setBorderPainted(false);
        borrar.setContentAreaFilled(false);
        borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos/borrar2.png"))); // NOI18N
        borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        borrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                borrarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nuevo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombreL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(nuevo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
    
         registrar();

    }//GEN-LAST:event_masActionPerformed

    private void nuevo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_tipoActionPerformed

    private void nuevo_tipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevo_tipoKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            registrar();
            
        }
      
    }//GEN-LAST:event_nuevo_tipoKeyPressed

    private void nuevo_tipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevo_tipoKeyReleased
        nuevo_tipo.setText(nuevo_tipo.getText().toUpperCase());
    }//GEN-LAST:event_nuevo_tipoKeyReleased

    private void nuevo_tipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevo_tipoKeyTyped
       
    }//GEN-LAST:event_nuevo_tipoKeyTyped

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        eliminar(""+productos.Productos.tipoAl1.getSelectedItem());
    }//GEN-LAST:event_borrarActionPerformed

    private void borrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_borrarKeyPressed
      
    }//GEN-LAST:event_borrarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton borrar;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JButton mas;
    public static javax.swing.JLabel nombreL;
    public static app.bolivia.swing.JCTextField nuevo_tipo;
    // End of variables declaration//GEN-END:variables
}
