/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.configuracion;

import java.awt.MouseInfo;
import java.awt.Point;

public class config extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuarios
     */
    public config() {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        contenido.setTitle("Informaciòn");
        informacion inf = new informacion();
        contenido.add(inf);       
        inf.toFront();
        inf.setVisible(true);
        contenido.setVisible(true);
      
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        info = new javax.swing.JButton();
        importar = new javax.swing.JButton();
        exportar = new javax.swing.JButton();
        configuracion = new javax.swing.JButton();
        contenido = new javax.swing.JInternalFrame();
        barraDeTitulo = new javax.swing.JPanel();
        miminizar = new javax.swing.JButton();
        miminizar1 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 37, 77), 4));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("CONFIGURACION");

        info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/informacion1.png"))); // NOI18N
        info.setText("Informacion");
        info.setBorder(null);
        info.setBorderPainted(false);
        info.setContentAreaFilled(false);
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        info.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/informacion2.png"))); // NOI18N
        info.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        importar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/importar1.png"))); // NOI18N
        importar.setText("Importar BD");
        importar.setBorder(null);
        importar.setBorderPainted(false);
        importar.setContentAreaFilled(false);
        importar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/importar2.png"))); // NOI18N
        importar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarActionPerformed(evt);
            }
        });

        exportar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/exportar1.png"))); // NOI18N
        exportar.setText("Exportar BD");
        exportar.setBorder(null);
        exportar.setBorderPainted(false);
        exportar.setContentAreaFilled(false);
        exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/exportar2.png"))); // NOI18N
        exportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        configuracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/configuracio1.png"))); // NOI18N
        configuracion.setText("Configuraìon");
        configuracion.setBorder(null);
        configuracion.setBorderPainted(false);
        configuracion.setContentAreaFilled(false);
        configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configuracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        configuracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/configuracio2.png"))); // NOI18N
        configuracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionActionPerformed(evt);
            }
        });

        contenido.setVisible(true);

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido.getContentPane());
        contenido.getContentPane().setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        barraDeTitulo.setBackground(new java.awt.Color(7, 37, 77));
        barraDeTitulo.setAlignmentX(0.0F);
        barraDeTitulo.setAlignmentY(0.0F);

        miminizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        miminizar.setForeground(new java.awt.Color(255, 255, 255));
        miminizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/close.png"))); // NOI18N
        miminizar.setBorder(null);
        miminizar.setContentAreaFilled(false);
        miminizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miminizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miminizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal/close2.png"))); // NOI18N
        miminizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        miminizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miminizarActionPerformed(evt);
            }
        });

        miminizar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        miminizar1.setForeground(new java.awt.Color(255, 255, 255));
        miminizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos/ico.png"))); // NOI18N
        miminizar1.setBorder(null);
        miminizar1.setContentAreaFilled(false);
        miminizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miminizar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miminizar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        miminizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miminizar1ActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CONFIGURACIONES");
        titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout barraDeTituloLayout = new javax.swing.GroupLayout(barraDeTitulo);
        barraDeTitulo.setLayout(barraDeTituloLayout);
        barraDeTituloLayout.setHorizontalGroup(
            barraDeTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeTituloLayout.createSequentialGroup()
                .addComponent(miminizar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(miminizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barraDeTituloLayout.setVerticalGroup(
            barraDeTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miminizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(miminizar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(importar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contenido)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barraDeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barraDeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(importar)
                        .addGap(18, 18, 18)
                        .addComponent(exportar)
                        .addGap(18, 18, 18)
                        .addComponent(configuracion)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addComponent(contenido)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed
        contenido.getContentPane().removeAll();
        contenido.setTitle("Importar");
        importar res = new importar();
        contenido.add(res);       
        res.toFront();
        res.setVisible(true);
         contenido.setVisible(true);
    }//GEN-LAST:event_importarActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        contenido.getContentPane().removeAll(); 
        contenido.setTitle("Exportar");
        respaldo res = new respaldo();
        contenido.add(res);       
        res.toFront();
        res.setVisible(true);
         contenido.setVisible(true);
    }//GEN-LAST:event_exportarActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        contenido.getContentPane().removeAll();
        contenido.setTitle("Informaciòn");
        informacion inf = new informacion();
        contenido.add(inf);       
        inf.toFront();
        inf.setVisible(true);
        contenido.setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    private void miminizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miminizarActionPerformed
        this.dispose();
    }//GEN-LAST:event_miminizarActionPerformed

    private void miminizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miminizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miminizar1ActionPerformed

    private void configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionActionPerformed
        contenido.getContentPane().removeAll(); 
        contenido.setTitle("Configuraciones");
        configuraciones con = new configuraciones();
        contenido.add(con);       
        con.toFront();
        con.setVisible(true);
        contenido.setVisible(true);
    }//GEN-LAST:event_configuracionActionPerformed

    private void tituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseDragged
       Point punto=MouseInfo.getPointerInfo().getLocation();
    
    int x=punto.x-200;
    int y=punto.y-150;
    
    int max_punto_X=798; 
    int max_punto_Y=247; 
    
    int max_pos_X=max_punto_X-200; 
    int max_pos_Y=max_punto_Y-150;
    
    
if((punto.x>=200 && punto.x<max_punto_X)  )
      this.setLocation(x,this.getY()); 

    if( (punto.y>=150 && punto.y<max_punto_Y) )
        this.setLocation(this.getX(),y);

    if(punto.x<200 )this.setLocation(3,this.getY());
    if(punto.x>max_punto_X)this.setLocation(max_pos_X,this.getY());
    if(punto.y<150 )this.setLocation(this.getX(),0);
    if(punto.y>max_punto_Y )this.setLocation(this.getX(),max_pos_Y);

 //this.setLocation(x,y);
 //System.out.println("x:"+this.getHeight()+" y:"+this.getWidth());
//System.out.println("x2:"+punto.x+" y2:"+punto.y);
    }//GEN-LAST:event_tituloMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraDeTitulo;
    private javax.swing.JButton configuracion;
    private javax.swing.JInternalFrame contenido;
    private javax.swing.JButton exportar;
    private javax.swing.JButton importar;
    private javax.swing.JButton info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton miminizar;
    private javax.swing.JButton miminizar1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
